[workspace]
resolver = "2"

members = [
    "fungible-token",
    "gear-feeds-router",
    "ping",
    "DAO",
    "fungible-token-messages",
    "non-fungible-token",
    "nft-example",
]

[profile.release]
lto = true
opt-level = "s"
